{% set name = "pop" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charmbracelet/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7f95a631ad84af09c9ba076348db92f4af5428087c3d03f6fc828b4c1c0084c7

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - pop --help

about:
  home: https://github.com/charmbracelet/pop
  dev_url: https://github.com/charmbracelet/pop
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Send emails from your terminal

extra:
  recipe-maintainers:
    - apcamargo
