{% set name = "pop" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charmbracelet/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1ac694148e286bf9bd75387a98ee66b41c554e989fae41314f4b762210e14436

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - pop --help

about:
  home: https://github.com/charmbracelet/pop
  dev_url: https://github.com/charmbracelet/pop
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Send emails from your terminal

extra:
  recipe-maintainers:
    - apcamargo
